flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-1.2.1.0
- ansi-terminal-0.6.3.1
- ansi-wl-pprint-0.6.8.1
- async-2.1.1.1
- attoparsec-0.13.2.0
- base-compat-0.9.3
- base-orphans-0.6
- base-prelude-1.2.0.1
- bifunctors-5.4.2
- cabal-doctest-1.0.2
- call-stack-0.1.0
- clock-0.7.2
- comonad-5.0.2
- conduit-1.2.11
- contravariant-1.4
- cryptohash-md5-0.11.100.1
- cryptohash-sha1-0.11.100.1
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.5.3
- dlist-0.8.0.3
- entropy-0.3.8
- exceptions-0.8.3
- fail-4.9.0.0
- foldl-1.3.0
- free-4.12.4
- hashable-1.2.6.1
- hostname-1.0
- integer-logarithms-1.0.2
- kan-extensions-5.0.2
- lens-4.15.4
- lifted-base-0.2.3.11
- managed-1.0.5
- math-functions-0.2.1.0
- mmorph-1.1.0
- monad-control-1.0.2.2
- mtl-2.2.1
- mwc-random-0.13.6.0
- network-info-0.2.0.8
- old-locale-1.0.0.7
- optional-args-1.0.1
- optparse-applicative-0.14.0.0
- parallel-3.2.1.1
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2.1
- random-1.1
- reflection-2.1.2
- resourcet-1.1.9
- scientific-0.3.5.1
- semigroupoids-5.2.1
- semigroups-0.18.3
- stm-2.4.4.1
- system-fileio-0.3.16.3
- system-filepath-0.4.13.4
- tagged-0.8.5
- temporary-1.2.1.1
- text-1.2.2.2
- th-abstraction-0.2.5.0
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- turtle-1.4.2
- unix-compat-0.4.3.1
- unordered-containers-0.2.8.0
- uuid-1.3.13
- uuid-types-1.0.3
- vector-0.12.0.1
- vector-builder-0.3.1
- vector-th-unbox-0.2.1.6
- void-0.7.2
- yaml-0.8.23.3
resolver: ghc-8.0.2
